/**
 * @goodies-beacon/core — shared vocabulary for every other package.
 *
 * P0-01 scaffold: domain schemas arrive in P1-02, database schema in P0-05.
 */
export const PACKAGE = '@goodies-beacon/core' as const;

export {
  createCookieJar,
  createMemoryCookieJar,
  parseSetCookie,
} from './adapter/cookies.js';
export {
  createHarness,
  type FixtureRoute,
  type Harness,
  type HarnessOptions,
  UnmatchedRequestError,
} from './adapter/harness.js';
export {
  createHttpClient,
  DEFAULT_MAX_DELAY_MS,
  DEFAULT_MIN_DELAY_MS,
  DEFAULT_TIMEOUT_MS,
  type HttpClientOptions,
  type RateLimitedClient,
} from './adapter/http.js';
export type {
  AdapterContext,
  BrowserFactory,
  BrowserPage,
  CookieJar,
  EnrichedListing,
  HealthResult,
  HealthStatus,
  HttpClient,
  PollMode,
  RawListing,
  SearchOptionDescriptor,
  SearchOptionSchema,
  SearchRequest,
  SourceAdapter,
} from './adapter/types.js';
export { ARGON2_OPTIONS, hashPassword, verifyPassword } from './auth/password.js';
export {
  type ChangePasswordInput,
  changePasswordSchema,
  type FirstRunInput,
  firstRunSchema,
  type LoginInput,
  loginSchema,
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  passwordSchema,
} from './auth/schemas.js';
export {
  createSession,
  createSessionToken,
  deleteOtherSessions,
  deleteSession,
  hashSessionToken,
  type IssuedSession,
  loadSession,
  SESSION_ID_BYTES,
  SESSION_REFRESH_AFTER_MS,
  SESSION_TTL_MS,
} from './auth/session.js';
export {
  AuthUserExistsError,
  createAuthUser,
  findAuthUser,
  USER_ID,
  updatePassword,
} from './auth/user.js';
export {
  type AiKeys,
  BAKED_VARIABLES,
  type Config,
  ConfigError,
  LOG_LEVELS,
  type LogLevel,
  loadConfigOrExit,
  parseConfig,
  ROLES,
  type Role,
} from './config.js';
export {
  DecryptionError,
  decryptSecret,
  encryptSecret,
  isEncrypted,
  secretsEqual,
} from './crypto.js';
export {
  CONNECT_TIMEOUT_MS,
  createDb,
  createPool,
  type Database,
  PING_TIMEOUT_MS,
  pingDatabase,
} from './db/client.js';
export { MIGRATIONS_FOLDER, runMigrations } from './db/migrate.js';
export {
  type AuthSession,
  type AuthUser,
  authSession,
  authUser,
  type Candidate,
  type CostLedgerEntry,
  candidates,
  costLedger,
  type Event,
  events,
  type Feedback,
  feedback,
  type GradingScale,
  gradingScales,
  type InstanceSecret,
  instanceSecret,
  type Listing,
  listings,
  type Media,
  media,
  type NewCandidate,
  type NewCostLedgerEntry,
  type NewListing,
  type NewMedia,
  type NewSpecVersion,
  type NewVerdict,
  type NewWantedItem,
  type Notification,
  notifications,
  type ProcessHeartbeat,
  processHeartbeat,
  type SearchPlanState,
  type Seen,
  type SettingsRow,
  type SpecVersion,
  searchPlanState,
  seen,
  settings,
  specVersions,
  type Verdict,
  verdicts,
  type WantedItem,
  wantedItems,
} from './db/schema.js';
export {
  AI_ROLES,
  type AiRole,
  BACKFILL_DEPTHS,
  type BackfillDepth,
  BUYING_TYPES,
  type BuyingType,
  CANDIDATE_ORIGINS,
  CANDIDATE_STAGES,
  type CandidateOrigin,
  type CandidateStage,
  CONDITION_CATEGORIES,
  type ConditionCategory,
  CRITERION_KINDS,
  CRITERION_RESULTS,
  type CriterionKind,
  type CriterionResult,
  EVENT_KINDS,
  EVENT_LEVELS,
  type EventKind,
  type EventLevel,
  FEEDBACK_RESOLUTIONS,
  FEEDBACK_TYPES,
  type FeedbackResolution,
  type FeedbackType,
  IMAGE_STRATEGIES,
  type ImageStrategy,
  MEDIA_KINDS,
  type MediaKind,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_MODES,
  type NotificationChannel,
  type NotificationMode,
  ON_UNKNOWN,
  type OnUnknown,
  REJECTION_REASONS,
  RELIST_POLICIES,
  type RejectionReason,
  type RelistPolicy,
  SHIPS_TO_UK,
  SHIPS_TO_UK_POLICIES,
  type ShipsToUk,
  type ShipsToUkPolicy,
  SPEC_ORIGINS,
  type SpecOrigin,
  VERDICT_DECISIONS,
  type VerdictDecision,
  WANTED_ITEM_STATUSES,
  type WantedItemStatus,
} from './domain/constants.js';
export {
  type DecidableCriterion,
  type Decision,
  type DecisionInput,
  decideVerdict,
  type GradeRank,
  resolveOnUnknown,
} from './domain/decide.js';
export {
  LINT_CODES,
  type LintCode,
  lintCriterion,
  lintSpec,
  type SpecWarning,
} from './domain/lint.js';
export {
  type ListingImage,
  listingImageSchema,
  type NormalisedListing,
  normalisedListingSchema,
  type RawListingShape,
  rawListingSchema,
} from './domain/listing.js';
export {
  loadSellerSalt,
  SELLER_SALT_BYTES,
  sellerHash,
  sellerHashesEqual,
} from './domain/seller.js';
export {
  backfillSchema,
  type Criterion,
  criterionSchema,
  durationSchema,
  type PriceCeiling,
  priceCeilingSchema,
  type ReferenceImage,
  referenceImageSchema,
  type SearchPlan,
  type SpecSettings,
  searchPlanSchema,
  specSettingsSchema,
  type WantedSpec,
  wantedSpecSchema,
} from './domain/spec.js';
export {
  type CriterionResultEntry,
  criterionResultSchema,
  MODEL_OUTPUT_SCHEMAS,
  type PrefilterOutput,
  prefilterOutputSchema,
  type ReviewerOutput,
  reviewerOutputSchema,
  type VerdictResult,
  verdictSchema,
} from './domain/verdict.js';
export { createLogger, createSilentLogger, type Logger } from './logger.js';
export {
  hammingDistance,
  looksLikeSameImage,
  perceptualHash,
  SAME_IMAGE_DISTANCE,
} from './media/hash.js';
export {
  type FetchImageOptions,
  fetchImage,
  findMedia,
  MAX_BYTES,
  MAX_REDIRECTS,
  MediaRejectedError,
  mediaPath,
  STORED_EDGE,
  type StoreImageOptions,
  storeImage,
  THUMBNAIL_EDGE,
} from './media/ingest.js';
export {
  assertFetchableUrl,
  assertPublicAddress,
  BlockedAddressError,
  isBlockedAddress,
  type Resolver,
} from './media/ssrf.js';
export {
  CACHE_TTL_MS,
  type Converted,
  type Converter,
  createConverter,
} from './money/convert.js';
export { RATES_CRON, RATES_QUEUE, ratesRefreshRegistration } from './money/job.js';
export {
  BASE_CURRENCY,
  convert,
  daysBetween,
  type EcbResponse,
  type FetchRatesOptions,
  fetchEcbRates,
  latestRate,
  RATES_URL,
  RatesUnavailableError,
  REQUIRED_CURRENCIES,
  type RefreshResult,
  rateOn,
  refreshRates,
  STALE_AFTER_DAYS,
} from './money/rates.js';
export {
  ensurePlanState,
  type IngestDeps,
  type IngestRequest,
  type IngestResult,
  ingestListings,
  recordPollFailure,
} from './poll/ingest.js';
export {
  durationToMinutes,
  IntervalError,
  type PollSchedule,
  pollSchedule,
  snapToExpressible,
  staggerOffset,
} from './poll/interval.js';
export { type ActivePlan, activePlans, findActivePlan } from './poll/plans.js';
export {
  type DesiredSchedule,
  desiredSchedules,
  type PollJobData,
  RECONCILE_CRON,
  type ReconcileDeps,
  type ReconcileResult,
  reconcileRegistration,
  reconcileSchedules,
} from './poll/reconcile.js';
export { type PollOutcome, type PollTarget, type RunPollOptions, runPoll } from './poll/run.js';
export { createBoss, QUEUE_SCHEMA } from './queue/boss.js';
export {
  HEARTBEAT_CRON,
  HEARTBEAT_STALE_AFTER_MS,
  heartbeatRegistration,
  recordHeartbeat,
} from './queue/heartbeat.js';
export {
  HEARTBEAT_ROLES,
  type HeartbeatRole,
  heartbeatQueueName,
  heartbeatRolesFor,
  pollQueueName,
  pollSourcesFor,
  REVIEW_QUEUE,
  SCHEDULE_QUEUE,
} from './queue/names.js';
export {
  assertUniqueQueues,
  DuplicateQueueError,
  type JobHandler,
  type QueueRegistration,
  registerQueues,
} from './queue/registry.js';
export {
  AI_PROVIDERS,
  type AiProvider,
  type AiSettings,
  aiSettingsSchema,
  DEFAULT_AI_ROLES,
  DEFAULT_BACKFILL_CAP,
  DEFAULT_DIGEST_TIME,
  DEFAULT_POLL_CAP,
  DEFAULT_POLL_INTERVAL,
  DEFAULT_SMTP_PORT,
  DEFAULT_TIMEZONE,
  type EbaySourceSettings,
  type EmailSettings,
  ebaySourceSchema,
  emailSettingsSchema,
  instanceSettingsSchema,
  isEbayConfigured,
  isEmailConfigured,
  modelRefSchema,
  type PollingSettings,
  type PublicProvider,
  type PublicSettings,
  parseModelRef,
  pollingSettingsSchema,
  providerCredential,
  type Settings,
  type SettingsPatch,
  SMTP_SECURITIES,
  type SmtpSecurity,
  type SourcesSettings,
  settingsPatchSchema,
  settingsSchema,
  sourcesSettingsSchema,
  toPublicSettings,
} from './settings/schema.js';
export {
  aiProvidersFromEnv,
  type EbayCredentials,
  readSettings,
  resolveAiProvider,
  resolveEbay,
  resolveSmtp,
  type SmtpCredentials,
  writeSettings,
} from './settings/store.js';
export { createShutdown, SHUTDOWN_TIMEOUT_MS, type Shutdown } from './shutdown.js';
export {
  isMarketplaceSourceId,
  isSourceId,
  MARKETPLACE_SOURCE_IDS,
  type MarketplaceSourceId,
  SOURCE_IDS,
  type SourceId,
  TEMPLATE_SOURCE_ID,
} from './sources.js';
