/**
 * @goodies-beacon/core/schemas — the validation the API and the web app must agree on.
 *
 * A separate entry point from the package root because the web app runs in a browser: the root
 * barrel reaches Postgres, pg-boss, pino and the native argon2 binding, none of which can be
 * bundled. Nothing imported from here may depend on those, and `schemas.test.ts` proves it.
 */

export {
  type ChangePasswordInput,
  changePasswordSchema,
  type FirstRunInput,
  firstRunSchema,
  type LoginInput,
  loginSchema,
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  passwordSchema,
} from './auth/schemas.js';
export {
  CANDIDATE_STAGE_LABELS,
  type CandidateDetail,
  type CandidateFilter,
  type CandidateList,
  type CandidateRow,
  type CriterionEvidence,
  candidateFilterSchema,
  type ListingView,
  retainSchema,
  type VerdictView,
} from './candidates/schema.js';
export {
  type Category,
  type CategorySaveInput,
  categoryIdSchema,
  categorySaveSchema,
} from './categories/schema.js';
export type {
  DashboardSummary,
  ItemCounts,
  SourceHealth,
  TodayCounts,
  WorkerLiveness,
} from './dashboard/schema.js';
export {
  AI_ROLES,
  type AiRole,
  BACKFILL_DEPTHS,
  type BackfillDepth,
  BUYING_TYPES,
  type BuyingType,
  CANDIDATE_ORIGINS,
  CANDIDATE_STAGES,
  CATEGORY_COLOURS,
  CATEGORY_ICONS,
  type CandidateOrigin,
  type CandidateStage,
  type CategoryColour,
  type CategoryIcon,
  CONDITION_CATEGORIES,
  type ConditionCategory,
  CRITERION_KINDS,
  type CriterionKind,
  type CriterionResult,
  IMAGE_STRATEGIES,
  type ImageStrategy,
  NOTIFICATION_MODES,
  type NotificationMode,
  ON_UNKNOWN,
  type OnUnknown,
  REJECTION_REASONS,
  RELIST_POLICIES,
  type RejectionReason,
  type RelistPolicy,
  SHIPS_TO_UK,
  SHIPS_TO_UK_POLICIES,
  type ShipsToUkPolicy,
  SPEC_ORIGINS,
  type SpecOrigin,
  VERDICT_DECISIONS,
  type VerdictDecision,
  WANTED_ITEM_STATUSES,
  type WantedItemStatus,
} from './domain/constants.js';
export {
  LINT_CODES,
  type LintCode,
  lintCriterion,
  lintSpec,
  type SpecWarning,
} from './domain/lint.js';
export {
  type ListingImage,
  listingImageSchema,
  type NormalisedListing,
  normalisedListingSchema,
} from './domain/listing.js';
export {
  backfillSchema,
  type Criterion,
  criterionSchema,
  durationSchema,
  type PriceCeiling,
  priceCeilingSchema,
  type ReferenceImage,
  referenceImageSchema,
  type SearchPlan,
  type SpecSettings,
  searchPlanSchema,
  specSettingsSchema,
  type WantedSpec,
  wantedSpecSchema,
} from './domain/spec.js';
export {
  joinTags,
  MAX_TAG_LENGTH,
  MAX_TAGS,
  matchesTag,
  splitTags,
  tagsSchema,
} from './domain/tags.js';
export {
  type CriterionResultEntry,
  criterionResultSchema,
  type PrefilterOutput,
  prefilterOutputSchema,
  type ReviewerOutput,
  reviewerOutputSchema,
  type VerdictResult,
  verdictSchema,
} from './domain/verdict.js';
export {
  type CandidateCounts,
  type ItemSaveInput,
  type ItemStatusInput,
  type ItemSummary,
  itemSaveSchema,
  itemStatusSchema,
  NEVER_POLLED,
  NO_CANDIDATES,
  type PlanStats,
  type PollState,
  type SpecVersionSummary,
} from './items/schema.js';
export {
  AI_PROVIDERS,
  type AiProvider,
  type AiSettings,
  aiSettingsSchema,
  DEFAULT_AI_ROLES,
  DEFAULT_DIGEST_TIME,
  DEFAULT_SMTP_PORT,
  DEFAULT_TIMEZONE,
  type EbaySourceSettings,
  type EmailSettings,
  ebaySourceSchema,
  emailSettingsSchema,
  instanceSettingsSchema,
  isEbayConfigured,
  isEmailConfigured,
  modelRefSchema,
  type PublicProvider,
  type PublicSettings,
  parseModelRef,
  type Settings,
  type SettingsPatch,
  SMTP_SECURITIES,
  type SmtpSecurity,
  type SourcesSettings,
  settingsPatchSchema,
  settingsSchema,
  sourcesSettingsSchema,
  toPublicSettings,
} from './settings/schema.js';
export {
  isMarketplaceSourceId,
  isSourceId,
  MARKETPLACE_SOURCE_IDS,
  type MarketplaceSourceId,
  SOURCE_IDS,
  type SourceId,
} from './sources.js';
export {
  type Wish,
  type WishSaveInput,
  wishSaveSchema,
} from './wishes/schema.js';
